vich_uploader:
    db_driver: orm

    mappings:
        peinture_images:
            uri_prefix: '%peinture_images%' #chemin mis dans services.yaml
            upload_destination: '%kernel.project_dir%/public%peinture_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
